import Head from "next/head";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Uzair S.",
  description: "Generated by create next app",
  manifest: "/site.webmanifest",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        {/* Link to the favicon.ico */}
        <link rel="icon" href="../favicon.ico" />
        {/* Link to the apple-touch-icon */}
        <link rel="apple-touch-icon" href="../public/apple-touch-icon.png" />
        {/* Link to the site.webmanifest */}
        <link rel="manifest" href={metadata.manifest} />
      </Head>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </>
  );
}
